### ISSUE TITLE
dpdk.spec no such file or directory 

### ISSUE THREAD

**Issue by duanwujie** [seladb/PcapPlusPlus#199]
```
root@debian:/home/linx/duan/PcapPlusPlus# ./configure-linux.sh 

****************************************
PcapPlusPlus Linux configuration script 
****************************************

Number of arguments: 0

Compile PcapPlusPlus with PF_RING? no
Compile PcapPlusPlus with DPDK? yes
Enter DPDK source path: /home/linx/duan/dpdk-19.05
grep: /home/linx/duan/dpdk-19.05/pkg/dpdk.spec: no such file or directory
PcapPlusPlus configuration is complete. Files created (or modified): mk/platform.mk, mk/PcapPlusPlus.mk, mk/install.sh, mk/uninstall.sh
````

no such file or directory

**Comment by seladb** [comment]
Thanks for reporting this issue.

Unfortunately DPDK 19.05 is not yet supported in PcapPlusPlus as you can read [here](http://seladb.github.io/PcapPlusPlus-Doc/dpdk-pf_ring.html). Only versions 16.11 to 19.02 (inclusive) were tested and officially supported. 

It's not easy to keep up with the changes going on in DPDK in each release, but I'll definitely address that in the near future.

Please let me know if you have more questions

**Comment by echo-Mike** [comment]
Hi @seladb!
Have You accidentally changed something inside DPDK docker containers during your "CMake adventure"?
Next error is a reoccurring one and the source is unknown:
https://travis-ci.org/echo-Mike/PcapPlusPlus/jobs/540493832
https://travis-ci.org/echo-Mike/PcapPlusPlus/jobs/540493831
https://travis-ci.org/echo-Mike/PcapPlusPlus/jobs/540493833
Onli this 3 out of 4 containers are affected

**Comment by seladb** [comment]
Oh @echo-Mike I'm so sorry, I did change something... I upgraded the DPDK versions in the docker containers. Please update your `.travis.yml` file as follows:

```
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1611
        - DPDK_DIR=dpdk-stable-16.11.9
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1711
        - DPDK_DIR=dpdk-stable-17.11.6
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1811
        - DPDK_DIR=dpdk-stable-18.11.1
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1902
        - DPDK_DIR=dpdk-19.02

```

But I don't think it'll solve the issue describe here with DPDK 19.05
